name = "chat-inja-online"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "chat-inja-online"

[env.development]
name = "chat-inja-online-dev"

[[d1_databases]]
binding = "DB"
database_name = "chat-inja-db"
database_id = "your-database-id-here"
